/**
 * Zustand store for solution plan state.
 * Stores the personalized solution plan generated by the AI
 * for rendering in the Esplora page.
 */

import { create } from 'zustand'

export interface WorkflowStep {
  useCaseId: string
  title: string
  description: string
}

export interface SolutionPlan {
  title: string
  subtitle?: string
  problem: {
    statement: string
    painPoints: string[]
  }
  workflow: {
    overview: string
    steps: WorkflowStep[]
  }
  comparison?: {
    before: string[]
    after: string[]
  }
  kpis?: {
    value: string
    label: string
    icon: string
  }[]
  useCases: {
    id: string
    customDescription: string
  }[]
  techStack?: string[]
  integrations?: string[]
}

interface SolutionPlanState {
  plan: SolutionPlan | null
  setPlan: (plan: SolutionPlan) => void
  clearPlan: () => void
}

export const useSolutionPlanStore = create<SolutionPlanState>((set) => ({
  plan: null,

  setPlan: (plan: SolutionPlan) => {
    set({ plan })
  },

  clearPlan: () => {
    set({ plan: null })
  },
}))
